# Generated by Django 4.2.13 on 2025-03-19 13:46

import api.users.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phoneverification_profile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='daysCommitTraining',
            field=models.JSONField(blank=True, null=True, validators=[api.users.validators.validate_days_of_week_list]),
        ),
        migrations.AddField(
            model_name='profile',
            name='diet',
            field=models.JSONField(blank=True, null=True, validators=[api.users.validators.validate_diet_list]),
        ),
        migrations.AddField(
            model_name='profile',
            name='distance',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='extraTraining',
            field=models.JSONField(blank=True, null=True, validators=[api.users.validators.validate_extra_training_list]),
        ),
        migrations.AddField(
            model_name='profile',
            name='feet',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='goals',
            field=models.JSONField(blank=True, null=True, validators=[api.users.validators.validate_goals_list]),
        ),
        migrations.AddField(
            model_name='profile',
            name='goalsDetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='heightCm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(250)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='inches',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(11)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='injuries',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='moreInfo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otherObligations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pastProblems',
            field=models.JSONField(blank=True, null=True, validators=[api.users.validators.validate_past_problems_list]),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferredLongRunDays',
            field=models.JSONField(blank=True, null=True, validators=[api.users.validators.validate_days_of_week_list]),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferredRestDays',
            field=models.JSONField(blank=True, null=True, validators=[api.users.validators.validate_days_of_week_list]),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferredWorkoutDays',
            field=models.JSONField(blank=True, null=True, validators=[api.users.validators.validate_days_of_week_list]),
        ),
        migrations.AddField(
            model_name='profile',
            name='raceDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='raceName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='recentRaceResults',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='routineAveragePace',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='routineDaysPerWeek',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='routineLongestRun',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='routineMilesPerRun',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='runningExperience',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='timeGoal',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weightKg',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddField(
            model_name='profile',
            name='weightLbs',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(22), django.core.validators.MaxValueValidator(1100)]),
        ),
    ]
