# Generated by Django 4.2.13 on 2025-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_age_profile_dayscommittraining_profile_diet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='daysCommitTraining',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
