# Generated by Django 4.2.13 on 2025-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_dayscommittraining'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_generating_training_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
