# Generated by Django 4.2.13 on 2025-03-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_is_generating_training_plan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_generating_training_plan',
        ),
    ]
