# Generated by Django 4.2.13 on 2025-04-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_is_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='routineMilesPerRun',
            new_name='routineMilesPerWeek',
        ),
    ]
