# Generated by Django 4.2.13 on 2025-04-09 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_routinemilesperrun_profile_routinemilesperweek'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='routineAveragePace',
            new_name='routineEasyPace',
        ),
    ]
