# Generated by Django 4.2.13 on 2025-03-20 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='planInfo',
            new_name='plan_info',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workoutInfo',
            new_name='workout_info',
        ),
    ]
