# Generated by Django 4.2.13 on 2025-03-25 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_alter_plan_options_workout_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='workout',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='completion_status',
            field=models.CharField(choices=[('completed', 'Completed as planned'), ('modified', 'Modified'), ('skipped', 'Skipped'), ('not_completed', 'Not completed')], default='not_completed', max_length=20),
        ),
        migrations.AddField(
            model_name='workout',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
