#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

# Migrate the database
python manage.py collectstatic --noinput
python manage.py migrate --noinput

echo "Starting Gunicorn (Production Mode)..."
exec gunicorn api.wsgi:application --bind 0.0.0.0:8000